### ISSUE TITLE
[TO-DO] Enhancements

### ISSUE THREAD

**Issue by alexlemaire** [alexlemaire/git-assist#55]
Various enhancements that can be done:

- [ ] custom implementation of `tail` module. I may not need the full module as is, so may be interesting to do a custom implementation to reduce package size. **Priority: low**
- [ ] expand docs for command calls. Add examples and develop on commands usage, also make sure that the feature table is up to date. May be worth auto generating the tables from docs. Auto documentation? **Priority: medium**
- [x] refactor `generate-ssh` and `generate-gpg` to work with config files instead of shell profile files so that it's easier to maintain and expand upon. Make sure that we can use the same commands across OS (`ssh-agent` one for example). Have a look if GPG/SSH passphrase cannot be stored in password managers. **Priority: high**
- [ ] refactor app logic. See #68. **Priority: critical**

**Comment by alexlemaire** [comment]
Refactored `generate-ssh` and `generate-gpg` through #69 and #70. Storing `ssh` passwords into password managers but not `gpg` as for now it should only run after user interaction so unattended mode doesn't seem very useful (by opposition with SSH which requires auto authentication when using the `auto-pull` feature)

**Comment by alexlemaire** [comment]
Moved this to `projects`, closing for now.
