### ISSUE TITLE
[TO-DO] Bugs

### ISSUE THREAD

**Issue by alexlemaire** [alexlemaire/git-assist#56]
Bugs to be fixed:

- [x] use `path.join()` to work with path to SSH key file instead of Linux convention inside of `generate-ssh` utility. This is to support OS other than Linux. Also check that SSH key storage is done the same way in other OS. **Priority: high**
- [ ] allow graceful shutdown even when stuck in `inquirer` prompt. **Priority: low**
- [ ] add `auto-pull` scheduled run resurrection support for _Windows_. Currently for _Windows_ `pm2` won't save the process list for resurrection without a plugin. So `startup` type of schedule won't work and `cron` wouldn't work if the machine is restarted. Have a look [here](https://pm2.keymetrics.io/docs/usage/startup/) and [there](https://www.npmjs.com/package/pm2-windows-startup). **Priority: medium**

**Comment by alexlemaire** [comment]
`generate-ssh` now supports Windows path style. Also supports inputting folders that do not exist yet.

See #60

**Comment by alexlemaire** [comment]
Moved tasks to `projects` instead. Cleaner approach. Closing for now
