### ISSUE TITLE
[TO-DO] Features

### ISSUE THREAD

**Issue by alexlemaire** [alexlemaire/git-assist#57]
Features to be implemented:

- [ ] setup automated testing. Should be done after #68 because new architecture would allow better/easier testing **Priority: high**
- [x] extend key generators so that user can add, list and delete keys (for now they can only add). **Priority: high**
- [x] add `easy-use` scripts for `logs` utility. **Priority: medium**
- [x] allows user to setup an automatic `auto-pull` run on machine startup and/or via _cron_ job (probably using [pm2](https://www.npmjs.com/package/pm2)). **Priority: high**
- [x] add option in `auto-pull` configuration to exclude some branches from `auto-pull` (in the same fashion as we exclude repos). **Priority: medium**

**Comment by alexlemaire** [comment]
`easy-use` scripts added for `logs` utility via #58 and #59

**Comment by alexlemaire** [comment]
Added `auto-pull` scheduling and branches exclusion via PRs #64 and #65

**Comment by alexlemaire** [comment]
`ssh` and `gpg` now handles generation, listing and deletion for keys. `git-assist` also manages its own keys instead of using an initial opinionated way. It also tries to leave enough freedom so that the package is able to work with SSH and GPG keys generated out of `git-assist` scope

**Comment by alexlemaire** [comment]
Moved to `projects`, closing for now.
